language: node_js
node_js:
- '8.12.0'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
- yarn install
script:
  - PORT=3000 yarn start &
  - sleep 3s;
  - curl -I http://localhost:3000 | grep -q '200 OK' || exit 1
cache:
  directories:
  - node_modules
